import '../cart_screen/widgets/cartitem1_item_widget.dart';import 'bloc/cart_bloc.dart';import 'models/cart_model.dart';import 'models/cartitem1_item_model.dart';import 'package:aayan_mateen_s_application1/core/app_export.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_leading_iconbutton_two.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_subtitle_one.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class CartScreen extends StatelessWidget {const CartScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<CartBloc>(create: (context) => CartBloc(CartState(cartModelObj: CartModel()))..add(CartInitialEvent()), child: CartScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: 371.h, padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 11.v), child: Column(children: [_buildPageDetails(context), SizedBox(height: 23.v), _buildCartItem1(context), SizedBox(height: 247.v), _buildLogin(context), SizedBox(height: 9.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 64.h, leading: AppbarLeadingIconbuttonTwo(imagePath: ImageConstant.imgArrowLeftBlueGray90003, margin: EdgeInsets.only(left: 24.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), title: AppbarSubtitleOne(text: "lbl_your_cart".tr, margin: EdgeInsets.only(left: 11.h))); } 
/// Section Widget
Widget _buildPageDetails(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("msg_2_items_in_your".tr, style: CustomTextStyles.bodyMediumOverpassBluegray90001_1)), Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgPlusIndigoA40001, height: 12.v, width: 11.h, margin: EdgeInsets.only(top: 3.v, bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 13.h), child: Text("lbl_add_more".tr, style: CustomTextStyles.bodyMediumOverpassIndigoA40001))])])); } 
/// Section Widget
Widget _buildCartItem1(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: BlocSelector<CartBloc, CartState, CartModel?>(selector: (state) => state.cartModelObj, builder: (context, cartModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: EdgeInsets.symmetric(vertical: 7.5.v), child: SizedBox(width: 322.h, child: Divider(height: 1.v, thickness: 1.v, color: appTheme.black90001.withOpacity(0.05))));}, itemCount: cartModelObj?.cartitem1ItemList.length ?? 0, itemBuilder: (context, index) {Cartitem1ItemModel model = cartModelObj?.cartitem1ItemList[index] ?? Cartitem1ItemModel(); return Cartitem1ItemWidget(model);});})); } 
/// Section Widget
Widget _buildLogin(BuildContext context) { return SizedBox(height: 206.v, width: 347.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 38.v), child: Text("msg_place_order_185_00".tr, style: CustomTextStyles.titleMediumOverpassWhiteA700))), Align(alignment: Alignment.center, child: Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: theme.colorScheme.primary, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder20), child: Container(height: 206.v, width: 347.h, decoration: AppDecoration.outlineIndigoA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgPattern, height: 206.v, width: 346.h, alignment: Alignment.center), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 11.h), child: Column(mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.only(left: 17.h, right: 21.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_order_total".tr, style: CustomTextStyles.titleSmallWhiteA700Medium), SizedBox(height: 5.v), Text("lbl_items_discount".tr, style: CustomTextStyles.titleSmallWhiteA700Medium), SizedBox(height: 7.v), Text("lbl_shipping".tr, style: CustomTextStyles.titleSmallWhiteA700Medium), SizedBox(height: 6.v), Text("lbl_total".tr, style: CustomTextStyles.bodyLargeAcmeWhiteA70001)])), Padding(padding: EdgeInsets.only(top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(right: 2.h), child: Text("lbl_120".tr, style: CustomTextStyles.bodyMediumAcmeWhiteA70001)), SizedBox(height: 9.v), Text("lbl_102".tr, style: CustomTextStyles.bodyMediumAcmeWhiteA70001), SizedBox(height: 7.v), Text("lbl_free".tr, style: CustomTextStyles.bodyMediumAcmeWhiteA70001), SizedBox(height: 11.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_130".tr, style: CustomTextStyles.bodyLargeAcmeWhiteA70001))]))])), SizedBox(height: 10.v), Container(width: 325.h, padding: EdgeInsets.symmetric(horizontal: 108.h, vertical: 12.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Text("lbl_pay_now".tr, style: CustomTextStyles.titleLargePrimary))])))]))))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
