name: aayan_mateen_s_application1
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  flutter_svg_provider: ^1.0.7
  smooth_page_indicator: ^1.1.0
  sms_autofill: ^2.3.0
  google_maps_flutter: ^2.5.0
  easy_date_timeline: ^1.0.2
  carousel_slider: ^4.2.1
  staggered_grid_view_flutter: ^0.0.4
  dotted_border: ^2.1.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Manrope
      fonts: 
        - asset: assets/fonts/ManropeBold.ttf
          weight: 700
        - asset: assets/fonts/ManropeMedium.ttf
          weight: 500
        - asset: assets/fonts/ManropeSemiBold.ttf
          weight: 600
    - family: Nunito Sans
      fonts: 
        - asset: assets/fonts/NunitoSansRegular.ttf
          weight: 400
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsBlack.ttf
          weight: 900
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratRomanBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratRomanMedium.ttf
          weight: 500
    - family: Overpass
      fonts: 
        - asset: assets/fonts/OverpassRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/OverpassBold.ttf
          weight: 700
        - asset: assets/fonts/OverpassRegular.ttf
          weight: 400
        - asset: assets/fonts/OverpassSemiBold.ttf
          weight: 600
        - asset: assets/fonts/OverpassRomanBold.ttf
          weight: 700
        - asset: assets/fonts/OverpassLight.ttf
          weight: 300
        - asset: assets/fonts/OverpassRomanRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
    - family: Urbanist
      fonts: 
        - asset: assets/fonts/UrbanistRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/UrbanistSemiBold.ttf
          weight: 600
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
    - family: Lato
      fonts: 
        - asset: assets/fonts/LatoBold.ttf
          weight: 700
        - asset: assets/fonts/LatoBlack.ttf
          weight: 900
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
    - family: Be Vietnam Pro
      fonts: 
        - asset: assets/fonts/BeVietnamProSemiBold.ttf
          weight: 600
        - asset: assets/fonts/BeVietnamProRegular.ttf
          weight: 400
        - asset: assets/fonts/BeVietnamProBold.ttf
          weight: 700
    - family: Acme
      fonts: 
        - asset: assets/fonts/AcmeRegular.ttf
          weight: 400
    - family: Abel
      fonts: 
        - asset: assets/fonts/AbelRegular.ttf
          weight: 400
