import 'bloc/pharmacy_bloc.dart';import 'dart:async';import 'models/pharmacy_model.dart';import 'package:aayan_mateen_s_application1/core/app_export.dart';import 'package:aayan_mateen_s_application1/presentation/search_doctors_one_page/search_doctors_one_page.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_subtitle_seven.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_subtitle_two.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_trailing_image_one.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:aayan_mateen_s_application1/widgets/custom_bottom_bar.dart';import 'package:aayan_mateen_s_application1/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';import 'package:google_maps_flutter/google_maps_flutter.dart';
// ignore_for_file: must_be_immutable
class PharmacyScreen extends StatelessWidget {PharmacyScreen({Key? key}) : super(key: key);

Completer<GoogleMapController> googleMapController = Completer();

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { return BlocProvider<PharmacyBloc>(create: (context) => PharmacyBloc(PharmacyState(pharmacyModelObj: PharmacyModel()))..add(PharmacyInitialEvent()), child: PharmacyScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<PharmacyBloc, PharmacyState>(builder: (context, state) {return SafeArea(child: Scaffold(body: SizedBox(height: SizeUtils.height, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgMap721x375, height: 721.v, width: 375.h, radius: BorderRadius.vertical(top: Radius.circular(25.h)), alignment: Alignment.bottomCenter), Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 16.v), _buildAppBar(context), SizedBox(height: 27.v), Container(height: 721.v, width: double.maxFinite, decoration: BoxDecoration(borderRadius: BorderRadiusStyle.customBorderTL25), child: Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(vertical: 30.v), decoration: AppDecoration.gradientWhiteAToWhiteA.copyWith(borderRadius: BorderRadiusStyle.customBorderTL25), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.end, children: [SizedBox(height: 64.v), _buildMap(context)]))))]))])), bottomNavigationBar: _buildBottomBar(context)));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 48.v, leadingWidth: 64.h, leading: Container(height: 45.v, width: 49.h, margin: EdgeInsets.only(left: 15.h, bottom: 3.v), child: Stack(alignment: Alignment.center, children: [Padding(padding: EdgeInsets.only(left: 9.h, bottom: 5.v), child: CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, decoration: IconButtonStyleHelper.outlineGrayTL101, alignment: Alignment.center, onTap: () {onTapBtnArrowLeft(context);}, child: CustomImageView(imagePath: ImageConstant.imgArrowLeftBlueGray90003))), CustomImageView(imagePath: ImageConstant.imgMegaphone, height: 13.v, width: 18.h, alignment: Alignment.center, margin: EdgeInsets.only(top: 32.v, right: 31.h))])), title: Container(height: 39.92.v, width: 185.h, margin: EdgeInsets.only(left: 5.h), child: Stack(alignment: Alignment.center, children: [AppbarSubtitleTwo(text: "lbl_pharmacy_nearby".tr, margin: EdgeInsets.only(bottom: 9.v)), AppbarSubtitleSeven(text: "lbl_search".tr, margin: EdgeInsets.only(left: 87.h, top: 21.v, right: 35.h))])), actions: [AppbarTrailingImageOne(imagePath: ImageConstant.imgThumbsUpWhiteA700, margin: EdgeInsets.fromLTRB(14.h, 32.v, 14.h, 3.v))]); } 
/// Section Widget
Widget _buildMap(BuildContext context) { return SizedBox(height: 597.v, width: 372.h, child: GoogleMap(mapType: MapType.normal, initialCameraPosition: CameraPosition(target: LatLng(37.43296265331129, -122.08832357078792), zoom: 14.4746), onMapCreated: (GoogleMapController controller) {googleMapController.complete(controller);}, zoomControlsEnabled: false, zoomGesturesEnabled: false, myLocationButtonEnabled: false, myLocationEnabled: false)); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Icongray500: return "/"; case BottomBarEnum.Icongray50023x26: return "/"; case BottomBarEnum.Searchblue50: return AppRoutes.searchDoctorsOnePage; case BottomBarEnum.Icongray50023x24: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.searchDoctorsOnePage: return SearchDoctorsOnePage.builder(context); default: return DefaultWidget();} } 

/// Navigates to the previous screen.
onTapBtnArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
