import 'bloc/terms_and_conditions_bloc.dart';import 'models/terms_and_conditions_model.dart';import 'package:aayan_mateen_s_application1/core/app_export.dart';import 'package:aayan_mateen_s_application1/presentation/search_doctors_one_page/search_doctors_one_page.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_leading_iconbutton_three.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_subtitle_eight.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:aayan_mateen_s_application1/widgets/custom_bottom_bar.dart';import 'package:aayan_mateen_s_application1/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class TermsAndConditionsScreen extends StatelessWidget {TermsAndConditionsScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { return BlocProvider<TermsAndConditionsBloc>(create: (context) => TermsAndConditionsBloc(TermsAndConditionsState(termsAndConditionsModelObj: TermsAndConditionsModel()))..add(TermsAndConditionsInitialEvent()), child: TermsAndConditionsScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<TermsAndConditionsBloc, TermsAndConditionsState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 2.v), child: Column(children: [SizedBox(height: 7.v), Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 14.h), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.customBorderTL25), child: Column(children: [SizedBox(height: 30.v), CustomElevatedButton(height: 40.v, text: "msg_last_uptade_27".tr, margin: EdgeInsets.only(left: 20.h, right: 19.h), buttonStyle: CustomButtonStyles.fillPrimary, buttonTextStyle: CustomTextStyles.bodyMediumPoppinsWhiteA700), SizedBox(height: 51.v), Container(width: 341.h, margin: EdgeInsets.only(right: 5.h), child: Text("msg_vivamus_ex_felis".tr, maxLines: 4, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumPoppinsBluegray40001.copyWith(height: 1.71))), SizedBox(height: 25.v), _buildDot(context), SizedBox(height: 25.v), Align(alignment: Alignment.centerLeft, child: Container(width: 331.h, margin: EdgeInsets.only(right: 15.h), child: Text("msg_vestibulum_consequat".tr, maxLines: 4, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumPoppinsBluegray40001.copyWith(height: 1.71)))), SizedBox(height: 14.v), Container(width: 341.h, margin: EdgeInsets.only(right: 5.h), child: Text("msg_vivamus_ex_felis2".tr, maxLines: 7, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumPoppinsBluegray40001.copyWith(height: 1.71)))]))])), bottomNavigationBar: _buildBottomBar(context)));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingIconbuttonThree(imagePath: ImageConstant.imgArrowLeftBlueGray90003, margin: EdgeInsets.only(left: 15.h, top: 11.v, bottom: 11.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleEight(text: "msg_terms_and_conditions2".tr.toUpperCase())); } 
/// Section Widget
Widget _buildDot(BuildContext context) { return Align(alignment: Alignment.centerLeft, child: Container(height: 174.v, width: 309.h, margin: EdgeInsets.only(left: 12.h), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topLeft, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 8.adaptSize, width: 8.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 58.v), decoration: BoxDecoration(color: appTheme.indigoA400, borderRadius: BorderRadius.circular(4.h))), Expanded(child: Container(width: 284.h, margin: EdgeInsets.only(left: 7.h), child: Text("msg_donec_molestie_ultricies".tr, maxLines: 3, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumPoppinsBluegray40001.copyWith(height: 1.71))))])), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 39.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 8.adaptSize, width: 8.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 58.v), decoration: BoxDecoration(color: appTheme.indigoA400, borderRadius: BorderRadius.circular(4.h))), Expanded(child: Container(width: 294.h, margin: EdgeInsets.only(left: 7.h), child: Text("msg_maecenas_pharetra".tr, maxLines: 3, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumPoppinsBluegray40001.copyWith(height: 1.71))))]))), Align(alignment: Alignment.bottomLeft, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 8.adaptSize, width: 8.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 34.v), decoration: BoxDecoration(color: appTheme.indigoA400, borderRadius: BorderRadius.circular(4.h))), Expanded(child: Container(width: 272.h, margin: EdgeInsets.only(left: 7.h), child: Text("msg_donec_commodo_gravida".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumPoppinsBluegray40001.copyWith(height: 1.71))))]))]))); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Icongray500: return "/"; case BottomBarEnum.Icongray50023x26: return "/"; case BottomBarEnum.Searchblue50: return AppRoutes.searchDoctorsOnePage; case BottomBarEnum.Icongray50023x24: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.searchDoctorsOnePage: return SearchDoctorsOnePage.builder(context); default: return DefaultWidget();} } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
