import 'bloc/payment_bloc.dart';import 'models/payment_model.dart';import 'package:aayan_mateen_s_application1/core/app_export.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_leading_iconbutton_one.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_subtitle_five.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:aayan_mateen_s_application1/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class PaymentScreen extends StatelessWidget {const PaymentScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<PaymentBloc>(create: (context) => PaymentBloc(PaymentState(paymentModelObj: PaymentModel()))..add(PaymentInitialEvent()), child: PaymentScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<PaymentBloc, PaymentState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(height: 611.v, width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 24.v), child: Stack(alignment: Alignment.topRight, children: [Align(alignment: Alignment.topCenter, child: Container(margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 191.v), decoration: AppDecoration.outlineBlack900015.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgImageRemovebgPreviewRedA700, height: 46.adaptSize, width: 46.adaptSize), Padding(padding: EdgeInsets.only(left: 14.h, bottom: 6.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_airtel".tr, style: CustomTextStyles.titleSmallInterGray90002Medium), SizedBox(height: 8.v), Text("msg".tr, style: CustomTextStyles.bodySmallGray90002)]))]))), CustomImageView(imagePath: ImageConstant.imgImageRemovebgPreviewRedA700380x105, height: 380.v, width: 105.h, alignment: Alignment.topRight, margin: EdgeInsets.only(top: 24.v))])), bottomNavigationBar: _buildAddNew(context)));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 56.h, leading: AppbarLeadingIconbuttonOne(imagePath: ImageConstant.imgArrowLeftGray90002, margin: EdgeInsets.only(left: 16.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleFive(text: "lbl_payment".tr), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgMegaphoneOnprimary, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 8.v))]); } 
/// Section Widget
Widget _buildAddNew(BuildContext context) { return CustomElevatedButton(text: "lbl_add_new".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 41.v), buttonStyle: CustomButtonStyles.fillPrimaryTL16, buttonTextStyle: CustomTextStyles.titleMediumWhiteA700); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
