import 'bloc/forgot_password_page_bloc.dart';import 'models/forgot_password_page_model.dart';import 'package:aayan_mateen_s_application1/core/app_export.dart';import 'package:aayan_mateen_s_application1/core/utils/validation_functions.dart';import 'package:aayan_mateen_s_application1/widgets/custom_elevated_button.dart';import 'package:aayan_mateen_s_application1/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class ForgotPasswordPageScreen extends StatelessWidget {ForgotPasswordPageScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<ForgotPasswordPageBloc>(create: (context) => ForgotPasswordPageBloc(ForgotPasswordPageState(forgotPasswordPageModelObj: ForgotPasswordPageModel()))..add(ForgotPasswordPageInitialEvent()), child: ForgotPasswordPageScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Form(key: _formKey, child: SizedBox(width: 430.h, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 128.v), Expanded(child: SingleChildScrollView(child: Container(margin: EdgeInsets.only(bottom: 117.v), padding: EdgeInsets.symmetric(horizontal: 32.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgGroupPrimary, height: 259.v, width: 301.h, alignment: Alignment.center), SizedBox(height: 90.v), Padding(padding: EdgeInsets.only(left: 29.h), child: Text("msg_forgot_password".tr, style: theme.textTheme.headlineLarge)), SizedBox(height: 15.v), Container(width: 284.h, margin: EdgeInsets.only(left: 30.h, right: 51.h), child: Text("msg_don_t_worry_it".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumMontserratOnErrorContainer)), SizedBox(height: 29.v), Align(alignment: Alignment.center, child: SizedBox(height: 63.v, width: 311.h, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topLeft, child: Text("lbl_email".tr, style: CustomTextStyles.bodyLargeBlack90001)), BlocSelector<ForgotPasswordPageBloc, ForgotPasswordPageState, TextEditingController?>(selector: (state) => state.emailController, builder: (context, emailController) {return CustomTextFormField(width: 311.h, controller: emailController, hintText: "msg_muhammadharis24".tr, hintStyle: CustomTextStyles.bodyMediumPoppinsBlack900, textInputAction: TextInputAction.done, textInputType: TextInputType.emailAddress, alignment: Alignment.bottomCenter, validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;}, contentPadding: EdgeInsets.symmetric(vertical: 7.v), borderDecoration: TextFormFieldStyleHelper.underLinePrimary, filled: false);})]))), SizedBox(height: 61.v), CustomElevatedButton(height: 50.v, text: "lbl_submit".tr, buttonStyle: CustomButtonStyles.fillBlueA, onPressed: () {onTapSubmit(context);})]))))]))))); } 
/// Navigates to the resetPasswordPageScreen when the action is triggered.
onTapSubmit(BuildContext context) { NavigatorService.pushNamed(AppRoutes.resetPasswordPageScreen, ); } 
 }
