import 'bloc/detail_doctor_address_tab_container_bloc.dart';import 'models/detail_doctor_address_tab_container_model.dart';import 'package:aayan_mateen_s_application1/core/app_export.dart';import 'package:aayan_mateen_s_application1/presentation/detail_doctor_address_page/detail_doctor_address_page.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_subtitle_five.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class DetailDoctorAddressTabContainerScreen extends StatefulWidget {const DetailDoctorAddressTabContainerScreen({Key? key}) : super(key: key);

@override DetailDoctorAddressTabContainerScreenState createState() =>  DetailDoctorAddressTabContainerScreenState();

static Widget builder(BuildContext context) { return BlocProvider<DetailDoctorAddressTabContainerBloc>(create: (context) => DetailDoctorAddressTabContainerBloc(DetailDoctorAddressTabContainerState(detailDoctorAddressTabContainerModelObj: DetailDoctorAddressTabContainerModel()))..add(DetailDoctorAddressTabContainerInitialEvent()), child: DetailDoctorAddressTabContainerScreen()); } 
 }

// ignore_for_file: must_be_immutable
class DetailDoctorAddressTabContainerScreenState extends State<DetailDoctorAddressTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 3, vsync: this); } 
@override Widget build(BuildContext context) { return BlocBuilder<DetailDoctorAddressTabContainerBloc, DetailDoctorAddressTabContainerState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 24.v), _buildDoctorInfo(context), SizedBox(height: 29.v), _buildTabview(context), Expanded(child: SizedBox(height: 533.v, child: TabBarView(controller: tabviewController, children: [DetailDoctorAddressPage.builder(context), DetailDoctorAddressPage.builder(context), DetailDoctorAddressPage.builder(context)])))]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 56.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeftGray90002, margin: EdgeInsets.only(left: 16.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleFive(text: "lbl_dr_randy_wigham".tr), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgDotsGray90002, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 8.v))]); } 
/// Section Widget
Widget _buildDoctorInfo(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgImage9, height: 74.adaptSize, width: 74.adaptSize, radius: BorderRadius.circular(12.h)), Padding(padding: EdgeInsets.only(left: 12.h, bottom: 4.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_dr_randy_wigham".tr, style: theme.textTheme.titleMedium), SizedBox(height: 6.v), SizedBox(width: 186.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_general".tr, style: CustomTextStyles.labelLargeInter_1), Text("lbl2".tr, style: theme.textTheme.labelLarge), Text("msg_rsud_gatot_subroto".tr, style: CustomTextStyles.labelLargeInter_1)])), SizedBox(height: 11.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgSignal, height: 16.adaptSize, width: 16.adaptSize), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_4_8".tr, style: theme.textTheme.labelLarge)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_4_279_reviews".tr, style: theme.textTheme.labelLarge))])])), CustomImageView(imagePath: ImageConstant.imgMessageTextBlueA400, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 30.h, top: 9.v, bottom: 41.v))])); } 
/// Section Widget
Widget _buildTabview(BuildContext context) { return Container(height: 44.v, width: 327.h, child: TabBar(controller: tabviewController, labelPadding: EdgeInsets.zero, labelColor: theme.colorScheme.primary, labelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w700), unselectedLabelColor: appTheme.gray50001, unselectedLabelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w700), indicator: BoxDecoration(border: Border(bottom: BorderSide(color: theme.colorScheme.primary, width: 2.h))), tabs: [Tab(child: Text("lbl_about_me2".tr)), Tab(child: Text("lbl_location2".tr)), Tab(child: Text("lbl_reviews".tr))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
