import '../rescheduled_details_screen/widgets/datetime_item_widget.dart';import 'bloc/rescheduled_details_bloc.dart';import 'models/datetime_item_model.dart';import 'models/rescheduled_details_model.dart';import 'package:aayan_mateen_s_application1/core/app_export.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_subtitle_five.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:aayan_mateen_s_application1/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class RescheduledDetailsScreen extends StatelessWidget {const RescheduledDetailsScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<RescheduledDetailsBloc>(create: (context) => RescheduledDetailsBloc(RescheduledDetailsState(rescheduledDetailsModelObj: RescheduledDetailsModel()))..add(RescheduledDetailsInitialEvent()), child: RescheduledDetailsScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 8.v), child: Column(children: [SizedBox(height: 1.v), Expanded(child: SingleChildScrollView(child: Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 21.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgTaddaaaImage, height: 145.v, width: 181.h, alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 60.h)), SizedBox(height: 12.v), Align(alignment: Alignment.centerRight, child: Container(width: 169.h, margin: EdgeInsets.only(right: 71.h), child: Text("msg_booking_has_been".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleLargeInterGray90002.copyWith(height: 1.40)))), SizedBox(height: 27.v), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("msg_booking_information".tr, style: CustomTextStyles.titleMediumSemiBold_1)), SizedBox(height: 27.v), _buildDateTime(context), SizedBox(height: 25.v), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("msg_doctor_information".tr, style: CustomTextStyles.titleMediumSemiBold_1)), SizedBox(height: 18.v), _buildCardDoctor(context)]))))])), bottomNavigationBar: _buildDone(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 56.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeftGray90002, margin: EdgeInsets.only(left: 16.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleFive(text: "lbl_details".tr)); } 
/// Section Widget
Widget _buildDateTime(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 6.h), child: BlocSelector<RescheduledDetailsBloc, RescheduledDetailsState, RescheduledDetailsModel?>(selector: (state) => state.rescheduledDetailsModelObj, builder: (context, rescheduledDetailsModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: rescheduledDetailsModelObj?.datetimeItemList.length ?? 0, itemBuilder: (context, index) {DatetimeItemModel model = rescheduledDetailsModelObj?.datetimeItemList[index] ?? DatetimeItemModel(); return DatetimeItemWidget(model);});})); } 
/// Section Widget
Widget _buildCardDoctor(BuildContext context) { return Container(margin: EdgeInsets.only(left: 6.h), padding: EdgeInsets.symmetric(vertical: 8.v), decoration: AppDecoration.white.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisSize: MainAxisSize.max, children: [CustomImageView(imagePath: ImageConstant.imgImage, height: 80.adaptSize, width: 80.adaptSize, radius: BorderRadius.circular(8.h)), Padding(padding: EdgeInsets.only(left: 16.h, top: 5.v, bottom: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_dr_randy_wigham".tr, style: theme.textTheme.titleMedium), SizedBox(height: 6.v), SizedBox(width: 186.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_general".tr, style: CustomTextStyles.labelLargeInter_1), Text("lbl2".tr, style: theme.textTheme.labelLarge), Text("msg_rsud_gatot_subroto".tr, style: CustomTextStyles.labelLargeInter_1)])), SizedBox(height: 11.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgSignal, height: 16.adaptSize, width: 16.adaptSize), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_4_8".tr, style: theme.textTheme.labelLarge)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_4_279_reviews".tr, style: theme.textTheme.labelLarge))])]))])); } 
/// Section Widget
Widget _buildDone(BuildContext context) { return CustomElevatedButton(text: "lbl_done".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 39.v), buttonStyle: CustomButtonStyles.fillBlueATL16, buttonTextStyle: CustomTextStyles.titleMediumWhiteA700); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
