import 'bloc/detail_doctor_about_me_tab_container_bloc.dart';import 'models/detail_doctor_about_me_tab_container_model.dart';import 'package:aayan_mateen_s_application1/core/app_export.dart';import 'package:aayan_mateen_s_application1/presentation/detail_doctor_about_me_page/detail_doctor_about_me_page.dart';import 'package:aayan_mateen_s_application1/presentation/detail_doctor_review_page/detail_doctor_review_page.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_subtitle_five.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class DetailDoctorAboutMeTabContainerScreen extends StatefulWidget {const DetailDoctorAboutMeTabContainerScreen({Key? key}) : super(key: key);

@override DetailDoctorAboutMeTabContainerScreenState createState() =>  DetailDoctorAboutMeTabContainerScreenState();

static Widget builder(BuildContext context) { return BlocProvider<DetailDoctorAboutMeTabContainerBloc>(create: (context) => DetailDoctorAboutMeTabContainerBloc(DetailDoctorAboutMeTabContainerState(detailDoctorAboutMeTabContainerModelObj: DetailDoctorAboutMeTabContainerModel()))..add(DetailDoctorAboutMeTabContainerInitialEvent()), child: DetailDoctorAboutMeTabContainerScreen()); } 
 }

// ignore_for_file: must_be_immutable
class DetailDoctorAboutMeTabContainerScreenState extends State<DetailDoctorAboutMeTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 3, vsync: this); } 
@override Widget build(BuildContext context) { return BlocBuilder<DetailDoctorAboutMeTabContainerBloc, DetailDoctorAboutMeTabContainerState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 24.v), child: Column(children: [_buildDoctorInfo(context), SizedBox(height: 29.v), _buildTabview(context), SizedBox(height: 585.v, child: TabBarView(controller: tabviewController, children: [DetailDoctorAboutMePage.builder(context), DetailDoctorAboutMePage.builder(context), DetailDoctorReviewPage.builder(context)]))])))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 56.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeftGray90002, margin: EdgeInsets.only(left: 16.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleFive(text: "lbl_dr_randy_wigham".tr), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgDotsGray90002, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 8.v))]); } 
/// Section Widget
Widget _buildDoctorInfo(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgImage9, height: 74.adaptSize, width: 74.adaptSize, radius: BorderRadius.circular(12.h)), Expanded(child: Padding(padding: EdgeInsets.only(left: 12.h, bottom: 4.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_dr_randy_wigham".tr, style: theme.textTheme.titleMedium), SizedBox(height: 6.v), SizedBox(width: 186.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_general".tr, style: CustomTextStyles.labelLargeInter_1), Text("lbl2".tr, style: theme.textTheme.labelLarge), Text("msg_rsud_gatot_subroto".tr, style: CustomTextStyles.labelLargeInter_1)]))]), CustomImageView(imagePath: ImageConstant.imgMessageTextBlueA400, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 30.h, top: 8.v, bottom: 9.v))]), SizedBox(height: 11.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgSignal, height: 16.adaptSize, width: 16.adaptSize), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_4_8".tr, style: theme.textTheme.labelLarge)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_4_279_reviews".tr, style: theme.textTheme.labelLarge))])])))])); } 
/// Section Widget
Widget _buildTabview(BuildContext context) { return Container(height: 44.v, width: 327.h, child: TabBar(controller: tabviewController, labelPadding: EdgeInsets.zero, labelColor: theme.colorScheme.primary, labelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w700), unselectedLabelColor: appTheme.gray50001, unselectedLabelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w700), indicator: BoxDecoration(border: Border(bottom: BorderSide(color: theme.colorScheme.primary, width: 2.h))), tabs: [Tab(child: Text("lbl_about_me2".tr)), Tab(child: Text("lbl_location".tr)), Tab(child: Text("lbl_reviews".tr))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
