import 'bloc/emergency_patient_two_tab_container_bloc.dart';import 'models/emergency_patient_two_tab_container_model.dart';import 'package:aayan_mateen_s_application1/core/app_export.dart';import 'package:aayan_mateen_s_application1/presentation/emergency_patient_two_page/emergency_patient_two_page.dart';import 'package:aayan_mateen_s_application1/presentation/search_doctors_one_page/search_doctors_one_page.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_subtitle_seven.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_subtitle_two.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_trailing_image_one.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:aayan_mateen_s_application1/widgets/custom_bottom_bar.dart';import 'package:aayan_mateen_s_application1/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';class EmergencyPatientTwoTabContainerScreen extends StatefulWidget {const EmergencyPatientTwoTabContainerScreen({Key? key}) : super(key: key);

@override EmergencyPatientTwoTabContainerScreenState createState() =>  EmergencyPatientTwoTabContainerScreenState();

static Widget builder(BuildContext context) { return BlocProvider<EmergencyPatientTwoTabContainerBloc>(create: (context) => EmergencyPatientTwoTabContainerBloc(EmergencyPatientTwoTabContainerState(emergencyPatientTwoTabContainerModelObj: EmergencyPatientTwoTabContainerModel()))..add(EmergencyPatientTwoTabContainerInitialEvent()), child: EmergencyPatientTwoTabContainerScreen()); } 
 }

// ignore_for_file: must_be_immutable
class EmergencyPatientTwoTabContainerScreenState extends State<EmergencyPatientTwoTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override void initState() { super.initState(); tabviewController = TabController(length: 2, vsync: this); } 
@override Widget build(BuildContext context) { return BlocBuilder<EmergencyPatientTwoTabContainerBloc, EmergencyPatientTwoTabContainerState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(height: 687.v, width: double.maxFinite, child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.bottomCenter, child: Container(decoration: AppDecoration.white.copyWith(borderRadius: BorderRadiusStyle.customBorderTL25), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 112.h), child: Text("lbl_transactions".tr, style: CustomTextStyles.titleMediumMontserratBlack90001)), SizedBox(height: 8.v), Container(height: 45.v, width: 288.h, margin: EdgeInsets.only(left: 33.h), decoration: BoxDecoration(color: appTheme.gray30001, borderRadius: BorderRadius.circular(13.h)), child: TabBar(controller: tabviewController, labelPadding: EdgeInsets.zero, labelColor: appTheme.whiteA700, labelStyle: TextStyle(fontSize: 13.524907112121582.fSize, fontFamily: 'Montserrat', fontWeight: FontWeight.w600), unselectedLabelColor: appTheme.black90001, unselectedLabelStyle: TextStyle(fontSize: 13.524907112121582.fSize, fontFamily: 'Montserrat', fontWeight: FontWeight.w600), indicatorPadding: EdgeInsets.all(3.0.h), indicator: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(13.h)), tabs: [Tab(child: Text("lbl_send".tr)), Tab(child: Text("lbl_apply".tr))])), _buildTabBarView(context)]))), _buildOrnament(context)])), bottomNavigationBar: _buildBottomBar(context)));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 54.v, leadingWidth: 53.h, leading: Container(height: 47.v, width: 40.h, margin: EdgeInsets.only(left: 13.h, top: 2.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgMegaphone, height: 13.v, width: 18.h, alignment: Alignment.center, margin: EdgeInsets.only(left: 2.h, right: 20.h, bottom: 34.v)), Padding(padding: EdgeInsets.only(top: 7.v), child: CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, decoration: IconButtonStyleHelper.outlineGrayTL101, alignment: Alignment.center, onTap: () {onTapBtnArrowLeft(context);}, child: CustomImageView(imagePath: ImageConstant.imgArrowLeftBlueGray90003)))])), title: Container(height: 46.75.v, width: 182.h, margin: EdgeInsets.only(left: 5.h), child: Stack(alignment: Alignment.bottomCenter, children: [AppbarSubtitleSeven(text: "lbl_search".tr, margin: EdgeInsets.only(left: 98.h, right: 21.h, bottom: 28.v)), AppbarSubtitleTwo(text: "msg_withdraw_earning".tr, margin: EdgeInsets.only(top: 16.v))])), actions: [AppbarTrailingImageOne(imagePath: ImageConstant.imgThumbsUpWhiteA700, margin: EdgeInsets.fromLTRB(14.h, 2.v, 14.h, 33.v))]); } 
/// Section Widget
Widget _buildTabBarView(BuildContext context) { return SizedBox(height: 385.v, child: TabBarView(controller: tabviewController, children: [EmergencyPatientTwoPage.builder(context), EmergencyPatientTwoPage.builder(context)])); } 
/// Section Widget
Widget _buildOrnament(BuildContext context) { return Align(alignment: Alignment.topLeft, child: SizedBox(height: 221.v, width: 332.h, child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.bottomRight, child: Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: theme.colorScheme.primary, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder16), child: Container(height: 193.v, width: 305.h, padding: EdgeInsets.symmetric(horizontal: 1.h), decoration: AppDecoration.primaryBlue.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgOrnament, height: 167.v, width: 299.h, alignment: Alignment.bottomCenter), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(left: 19.h, right: 19.h, bottom: 18.v), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(crossAxisAlignment: CrossAxisAlignment.end, children: [Text("msg_0329".tr, style: CustomTextStyles.titleLargeLatoGray50), Container(width: 20.h, margin: EdgeInsets.only(left: 18.h, top: 6.v, bottom: 3.v), child: Text("lbl_valid_thru".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.poppinsWhiteA700)), Padding(padding: EdgeInsets.only(left: 4.h, top: 4.v, bottom: 2.v), child: Text("lbl_03_24".tr, style: CustomTextStyles.labelLargePoppinsWhiteA700))]), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(right: 22.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 7.v), child: Text("lbl_muhammad_haris".tr.toUpperCase(), style: CustomTextStyles.titleSmallWhiteA700)), CustomImageView(imagePath: ImageConstant.imgUserAmber400, height: 24.v, width: 42.h, margin: EdgeInsets.only(bottom: 5.v))]))])))])))), CustomImageView(imagePath: ImageConstant.imgImageRemovebgPreview, height: 145.v, width: 204.h, alignment: Alignment.topLeft)]))); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Icongray500: return "/"; case BottomBarEnum.Icongray50023x26: return "/"; case BottomBarEnum.Searchblue50: return AppRoutes.searchDoctorsOnePage; case BottomBarEnum.Icongray50023x24: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.searchDoctorsOnePage: return SearchDoctorsOnePage.builder(context); default: return DefaultWidget();} } 

/// Navigates to the previous screen.
onTapBtnArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
