import 'bloc/emergency_patient_bloc.dart';import 'dart:async';import 'models/emergency_patient_model.dart';import 'package:aayan_mateen_s_application1/core/app_export.dart';import 'package:aayan_mateen_s_application1/presentation/search_doctors_one_page/search_doctors_one_page.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_subtitle_seven.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_subtitle_two.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_trailing_image_one.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:aayan_mateen_s_application1/widgets/custom_bottom_bar.dart';import 'package:aayan_mateen_s_application1/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';import 'package:google_maps_flutter/google_maps_flutter.dart';
// ignore_for_file: must_be_immutable
class EmergencyPatientScreen extends StatelessWidget {EmergencyPatientScreen({Key? key}) : super(key: key);

Completer<GoogleMapController> googleMapController = Completer();

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { return BlocProvider<EmergencyPatientBloc>(create: (context) => EmergencyPatientBloc(EmergencyPatientState(emergencyPatientModelObj: EmergencyPatientModel()))..add(EmergencyPatientInitialEvent()), child: EmergencyPatientScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<EmergencyPatientBloc, EmergencyPatientState>(builder: (context, state) {return SafeArea(child: Scaffold(body: SizedBox(height: SizeUtils.height, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 5.v), _buildAppBar(context), SizedBox(height: 736.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(height: 721.v, width: double.maxFinite, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.vertical(top: Radius.circular(25.h))))), _buildSearchMap(context)]))])), CustomImageView(imagePath: ImageConstant.imgMap, height: 721.v, width: 373.h, radius: BorderRadius.vertical(top: Radius.circular(25.h)), alignment: Alignment.bottomCenter, margin: EdgeInsets.only(bottom: 25.v))])), bottomNavigationBar: _buildBottomBar(context)));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 49.v, leadingWidth: 53.h, leading: Container(height: 47.v, width: 40.h, margin: EdgeInsets.only(left: 13.h, top: 2.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgMegaphone, height: 13.v, width: 18.h, alignment: Alignment.center, margin: EdgeInsets.only(left: 2.h, right: 20.h, bottom: 34.v)), Padding(padding: EdgeInsets.only(top: 7.v), child: CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, decoration: IconButtonStyleHelper.outlineGrayTL101, alignment: Alignment.center, onTap: () {onTapBtnArrowLeft(context);}, child: CustomImageView(imagePath: ImageConstant.imgArrowLeftBlueGray90003)))])), title: Container(height: 44.1.v, width: 164.h, margin: EdgeInsets.only(left: 5.h), child: Stack(alignment: Alignment.topCenter, children: [AppbarSubtitleSeven(text: "lbl_search".tr, margin: EdgeInsets.only(left: 98.h, right: 3.h, bottom: 26.v)), AppbarSubtitleTwo(text: "msg_patient_location".tr, margin: EdgeInsets.only(top: 14.v))])), actions: [AppbarTrailingImageOne(imagePath: ImageConstant.imgThumbsUpWhiteA700, margin: EdgeInsets.fromLTRB(14.h, 2.v, 14.h, 33.v))]); } 
/// Section Widget
Widget _buildSearchMap(BuildContext context) { return SizedBox(height: 721.v, width: 373.h, child: GoogleMap(mapType: MapType.normal, initialCameraPosition: CameraPosition(target: LatLng(37.43296265331129, -122.08832357078792), zoom: 14.4746), onMapCreated: (GoogleMapController controller) {googleMapController.complete(controller);}, zoomControlsEnabled: false, zoomGesturesEnabled: false, myLocationButtonEnabled: false, myLocationEnabled: false)); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Icongray500: return "/"; case BottomBarEnum.Icongray50023x26: return "/"; case BottomBarEnum.Searchblue50: return AppRoutes.searchDoctorsOnePage; case BottomBarEnum.Icongray50023x24: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.searchDoctorsOnePage: return SearchDoctorsOnePage.builder(context); default: return DefaultWidget();} } 

/// Navigates to the previous screen.
onTapBtnArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
