import 'bloc/address_bloc.dart';import 'models/address_model.dart';import 'package:aayan_mateen_s_application1/core/app_export.dart';import 'package:aayan_mateen_s_application1/core/utils/validation_functions.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_leading_iconbutton_two.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/appbar_subtitle.dart';import 'package:aayan_mateen_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:aayan_mateen_s_application1/widgets/custom_checkbox_button.dart';import 'package:aayan_mateen_s_application1/widgets/custom_elevated_button.dart';import 'package:aayan_mateen_s_application1/widgets/custom_icon_button.dart';import 'package:aayan_mateen_s_application1/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class AddressScreen extends StatelessWidget {AddressScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<AddressBloc>(create: (context) => AddressBloc(AddressState(addressModelObj: AddressModel()))..add(AddressInitialEvent()), child: AddressScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: SingleChildScrollView(padding: EdgeInsets.only(top: 25.v), child: Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 18.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildRowContrast(context), SizedBox(height: 12.v), _buildRowFrame(context), SizedBox(height: 41.v), Padding(padding: EdgeInsets.only(left: 12.h), child: Text("lbl_full_name2".tr, style: CustomTextStyles.titleLargeInterBluegray90002_1)), SizedBox(height: 11.v), _buildEditTextFullName(context), SizedBox(height: 32.v), Padding(padding: EdgeInsets.only(left: 12.h), child: Text("lbl_email_address".tr, style: CustomTextStyles.titleLargeInterBluegray90002_1)), SizedBox(height: 11.v), _buildEditTextEmailAddress(context), SizedBox(height: 32.v), Padding(padding: EdgeInsets.only(left: 12.h), child: Text("lbl_phone_number".tr, style: CustomTextStyles.titleLargeInterBluegray90002_1)), SizedBox(height: 11.v), _buildEditTextPhoneNumber(context), SizedBox(height: 32.v), Padding(padding: EdgeInsets.only(left: 12.h), child: Text("lbl_address".tr, style: CustomTextStyles.titleLargeInterBluegray90002_1)), SizedBox(height: 11.v), _buildEditTextAddress(context), SizedBox(height: 34.v), _buildZipCode(context), SizedBox(height: 21.v), _buildCheckBoxSaveShippingAddress(context), SizedBox(height: 51.v), _buildButtonNext(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 95.h, leading: AppbarLeadingIconbuttonTwo(imagePath: ImageConstant.imgArrowLeftBlueGray90003, margin: EdgeInsets.only(left: 55.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), title: AppbarSubtitle(text: "lbl_checkout".tr, margin: EdgeInsets.only(left: 39.h))); } 
/// Section Widget
Widget _buildRowContrast(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 12.h, right: 29.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgContrastPrimary, height: 43.adaptSize, width: 43.adaptSize), SizedBox(height: 43.v, width: 229.h, child: Stack(alignment: Alignment.centerRight, children: [Align(alignment: Alignment.center, child: SizedBox(width: 227.h, child: Divider(color: appTheme.blueGray100))), Align(alignment: Alignment.centerRight, child: Container(height: 43.adaptSize, width: 43.adaptSize, padding: EdgeInsets.all(3.h), decoration: AppDecoration.outlineDeepOrangeA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: CustomIconButton(height: 37.adaptSize, width: 37.adaptSize, padding: EdgeInsets.all(9.h), decoration: IconButtonStyleHelper.fillPrimary, alignment: Alignment.center, child: CustomImageView(imagePath: ImageConstant.imgCheckmark))))]))])); } 
/// Section Widget
Widget _buildRowFrame(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 12.h, right: 27.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("lbl_address".tr, style: CustomTextStyles.titleMediumBluegray90002)), Text("lbl_delivery".tr, textAlign: TextAlign.center, style: CustomTextStyles.titleMediumBluegray90002)])); } 
/// Section Widget
Widget _buildEditTextFullName(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 12.h, right: 4.h), child: BlocSelector<AddressBloc, AddressState, TextEditingController?>(selector: (state) => state.editTextFullNameController, builder: (context, editTextFullNameController) {return CustomTextFormField(controller: editTextFullNameController, hintText: "lbl_muhammad_haris".tr, hintStyle: CustomTextStyles.titleMediumBluegray90002);})); } 
/// Section Widget
Widget _buildEditTextEmailAddress(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 12.h, right: 4.h), child: BlocSelector<AddressBloc, AddressState, TextEditingController?>(selector: (state) => state.editTextEmailAddressController, builder: (context, editTextEmailAddressController) {return CustomTextFormField(controller: editTextEmailAddressController, hintText: "msg_1369857265_gmail_com".tr, hintStyle: CustomTextStyles.titleMediumBluegray90002, textInputType: TextInputType.emailAddress, validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;});})); } 
/// Section Widget
Widget _buildEditTextPhoneNumber(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 12.h, right: 4.h), child: BlocSelector<AddressBloc, AddressState, TextEditingController?>(selector: (state) => state.editTextPhoneNumberController, builder: (context, editTextPhoneNumberController) {return CustomTextFormField(controller: editTextPhoneNumberController, hintText: "msg_enter_your_phone".tr, hintStyle: CustomTextStyles.titleMediumBluegray90002, textInputType: TextInputType.phone, validator: (value) {if (!isValidPhone(value)) {return "err_msg_please_enter_valid_phone_number".tr;} return null;});})); } 
/// Section Widget
Widget _buildEditTextAddress(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 12.h, right: 4.h), child: BlocSelector<AddressBloc, AddressState, TextEditingController?>(selector: (state) => state.editTextAddressController, builder: (context, editTextAddressController) {return CustomTextFormField(controller: editTextAddressController, hintText: "msg_enter_your_address".tr, hintStyle: CustomTextStyles.titleMediumOnPrimaryContainer);})); } 
/// Section Widget
Widget _buildEditTextZipCode(BuildContext context) { return BlocSelector<AddressBloc, AddressState, TextEditingController?>(selector: (state) => state.editTextZipCodeController, builder: (context, editTextZipCodeController) {return CustomTextFormField(width: 170.h, controller: editTextZipCodeController, hintText: "lbl_zip_code".tr, hintStyle: CustomTextStyles.titleMediumOnPrimaryContainer, textInputType: TextInputType.number, validator: (value) {if (!isNumeric(value)) {return "err_msg_please_enter_valid_number".tr;} return null;});}); } 
/// Section Widget
Widget _buildEditTextCity(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(left: 11.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_city".tr, style: CustomTextStyles.titleLargeInterBluegray90002_1), SizedBox(height: 10.v), BlocSelector<AddressBloc, AddressState, TextEditingController?>(selector: (state) => state.cityController, builder: (context, cityController) {return CustomTextFormField(width: 170.h, controller: cityController, hintText: "lbl_city".tr, hintStyle: CustomTextStyles.titleMediumOnPrimaryContainer, textInputAction: TextInputAction.done);})]))); } 
/// Section Widget
Widget _buildZipCode(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 12.h, right: 4.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 11.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_zip_code".tr, style: CustomTextStyles.titleLargeInterBluegray90002_1), SizedBox(height: 10.v), _buildEditTextZipCode(context)]))), _buildEditTextCity(context)])); } 
/// Section Widget
Widget _buildCheckBoxSaveShippingAddress(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 12.h), child: BlocSelector<AddressBloc, AddressState, bool?>(selector: (state) => state.checkBoxSaveShippingAddress, builder: (context, checkBoxSaveShippingAddress) {return CustomCheckboxButton(text: "msg_save_shipping_address".tr, value: checkBoxSaveShippingAddress, onChange: (value) {context.read<AddressBloc>().add(ChangeCheckBoxEvent(value: value));});})); } 
/// Section Widget
Widget _buildButtonNext(BuildContext context) { return CustomElevatedButton(height: 70.v, text: "lbl_next".tr, margin: EdgeInsets.only(left: 16.h), buttonStyle: CustomButtonStyles.fillPrimary, buttonTextStyle: CustomTextStyles.titleLargeInter); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
